_options:
  content:
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    numberedlist: true
    code: true
    table: true
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    subscript: true
    superscript: true
    image: true
    bulletedlist: true
    styles: /editor.css